import '../modules/message/model/chat_list_model.dart';
import '../modules/message/model/message_model.dart';
import '../modules/notification/model/notification_model.dart';
import '../modules/order/model/product_model.dart';
import '../modules/order/model/product_order_model.dart';
import '../modules/setting/model/faq_model.dart';

final notificationList = [
  NotificationModel(
      id: 0,
      text: '50% OFF in Ultraboost All Terrain ltd Shoes!!',
      time: '9:35AM',
      image: 'https://picsum.photos/50/50'),
  NotificationModel(
      id: 1,
      text: 'New amagizing collection for our Topcommres',
      time: '6:35AM',
      image: 'https://picsum.photos/50/50'),
  NotificationModel(
      id: 2,
      text: 'Your get amazing gift for Shop Bulli.',
      time: '4:35AM',
      image: 'https://picsum.photos/50/50'),
  NotificationModel(
      id: 3,
      text: '33% OFF in Ultraboost All Terrain ltd Shoes!!',
      time: '2:35AM',
      image: 'https://picsum.photos/50/50'),
  NotificationModel(
      id: 4,
      text: 'Free ! in bike cover in R15 V3 BS6 !!',
      time: '11:35AM',
      image: 'https://picsum.photos/50/50'),
  NotificationModel(
      id: 3,
      text: '33% OFF in Ultraboost All Terrain ltd Shoes!!',
      time: '2:35AM',
      image: 'https://picsum.photos/50/50'),
  NotificationModel(
      id: 4,
      text: 'Free ! in bike cover in R15 V3 BS6 !!',
      time: '11:35AM',
      image: 'https://picsum.photos/50/50'),
  NotificationModel(
      id: 3,
      text: '33% OFF in Ultraboost All Terrain ltd Shoes!!',
      time: '2:35AM',
      image: 'https://picsum.photos/50/50'),
  NotificationModel(
      id: 4,
      text: 'Free ! in bike cover in R15 V3 BS6 !!',
      time: '11:35AM',
      image: 'https://picsum.photos/50/50'),
];
final chatMessageList = [
  MessageModel(
    id: 0,
    dateTime: DateTime.now(),
    isMe: true,
    text: 'Sound null safety support!',
  ),
  MessageModel(
    id: 1,
    dateTime: DateTime.now(),
    isMe: true,
    text: 'Add the package to your pubspec.yaml',
  ),
  MessageModel(
    id: 2,
    dateTime: DateTime.now(),
    isMe: true,
    text: 'Almost all fields from ListView.builder available.',
  ),
  MessageModel(
    id: 3,
    dateTime: DateTime.now(),
    isMe: true,
    text: 'Sound null safety support!',
  ),
  MessageModel(
    id: 4,
    dateTime: DateTime.now(),
    isMe: true,
    text: 'For the groups an individual header can be set.',
  ),
  MessageModel(
    id: 5,
    dateTime: DateTime.now(),
    isMe: false,
    text: 'List Items can be separated in groups.',
  ),
  MessageModel(
    id: 6,
    dateTime: DateTime.now().subtract(const Duration(days: 3)),
    isMe: true,
    text: 'Sound null safety support!',
  ),
  MessageModel(
    id: 7,
    dateTime: DateTime.now().subtract(const Duration(days: 4)),
    isMe: false,
    text: 'Easy creation of chat dialog.',
  ),
  MessageModel(
    id: 4,
    dateTime: DateTime.now().subtract(const Duration(days: 1)),
    isMe: false,
    text: 'For the groups an individual header can be set.',
  ),
  MessageModel(
    id: 5,
    dateTime: DateTime.now(),
    isMe: false,
    text: 'List Items can be separated in groups.',
  ),
  MessageModel(
    id: 6,
    dateTime: DateTime.now().subtract(const Duration(days: 3)),
    isMe: true,
    text: 'Sound null safety support!',
  ),
  MessageModel(
    id: 7,
    dateTime: DateTime.now().subtract(const Duration(days: 4)),
    isMe: false,
    text: 'Easy creation of chat dialog.',
  ),
];

final chatList = [
  const ChatListModel(
      id: 0,
      image: '',
      msg: 'What is the size the',
      name: 'Harry Potter Film',
      dateTime: '10:00',
      numberOfMsg: '3'),
  const ChatListModel(
      id: 1,
      image: '',
      msg: 'What is the size the',
      name: 'Harry Potter Film',
      dateTime: '10:01',
      numberOfMsg: '1'),
  const ChatListModel(
      id: 2,
      image: '',
      msg: 'Nike',
      name: 'This is going to cost Potter Film',
      dateTime: '10:03',
      numberOfMsg: ''),
];

final orderProductList = [
  OrderedProductModel(
    id: 120,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    price: 121,
    name: 'Fashion Shoes Men',
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 3,
    orderNumber: '35464',
    status: 'processing',
    trakignNumber: 'IW3475453455',
    productList: populerProductList,
  ),
  OrderedProductModel(
    id: 130,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    name: 'Fashion Shoes Men',
    price: 121,
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 3,
    orderNumber: '35464',
    status: 'delivered',
    trakignNumber: 'IW3475453455',
    productList: populerProductList,
  ),
  OrderedProductModel(
    id: 0,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    price: 121,
    name: 'Fashion Shoes Men',
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 3,
    orderNumber: '35464',
    status: 'delivered',
    trakignNumber: 'IW3475453455',
    productList: populerProductList,
  ),
  OrderedProductModel(
    id: 1,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    price: 125,
    name: 'Fashion Shoes Men',
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 9,
    orderNumber: '546464',
    status: 'delivered',
    trakignNumber: 'dffg43536895685',
    productList: populerProductList,
  ),
  OrderedProductModel(
    id: 2,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    price: 12,
    name: 'Fashion Shoes Men',
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 90,
    orderNumber: '540064',
    status: 'Cancelled',
    trakignNumber: 'dfghf98dfjngj',
    productList: populerProductList,
  ),
  OrderedProductModel(
    id: 3,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    name: 'Fashion Shoes Men',
    price: 150,
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 190,
    orderNumber: '56856',
    status: 'Cancelled',
    trakignNumber: 'wigtgg450978687',
    productList: populerProductList,
  ),
  OrderedProductModel(
    id: 4,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    price: 170,
    name: 'Fashion Shoes Men',
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 290,
    orderNumber: '596786',
    status: 'Cancelled',
    trakignNumber: 'omarfasj886u78678',
    productList: populerProductList,
  ),
  OrderedProductModel(
    id: 5,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    price: 30,
    name: 'Fashion Shoes Men',
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 45,
    orderNumber: '568568',
    status: 'Cancelled',
    trakignNumber: 'omarfasj886u78678',
    productList: populerProductList,
  ),
  OrderedProductModel(
    id: 6,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    price: 30,
    name: 'Fashion Shoes Men',
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 45,
    orderNumber: '568568',
    status: 'Delivered',
    trakignNumber: 'omarfasj886u78678',
    productList: populerProductList,
  ),
  OrderedProductModel(
    id: 7,
    invoice: "GR-44234",
    orderDeliveryTime: '12:43PM',
    paymentType: 'Cash on Delivery',
    price: 30,
    name: 'Fashion Shoes Men',
    image: "https://via.placeholder.com/150",
    orderDate: DateTime.now().toIso8601String(),
    quantity: 45,
    orderNumber: '568568',
    status: 'Delivered',
    trakignNumber: 'omarfasj886u78678',
    productList: populerProductList,
  ),
];

final populerProductList = [
  const ProductModel(
    id: 0,
    name: 'Fashion Shoes Men',
    categoryName: "Man's Fashion",
    rating: 3,
    price: 39.0,
    offer: 55,
    offerPrice: 85,
    image: 'https://picsum.photos/id/21/160/120',
    totalStock: 2,
  ),
  const ProductModel(
    id: 1,
    name: 'Fashion Shoes Men',
    categoryName: "Electronics",
    rating: 3,
    price: 39.0,
    offer: 55,
    offerPrice: 85,
    image: 'https://picsum.photos/id/7/160/120',
    totalStock: 1,
  ),
  const ProductModel(
    id: 2,
    name: 'Fashion Shoes Men',
    categoryName: "Man's Fashion",
    rating: 3,
    price: 39.0,
    offer: 55,
    offerPrice: 85,
    image: 'https://picsum.photos/id/2/160/120',
    totalStock: 6,
  ),
  const ProductModel(
    id: 3,
    name: 'Fashion Shoes Men',
    categoryName: "Bike",
    rating: 3,
    price: 39.0,
    offer: 55,
    offerPrice: 85,
    image: 'https://picsum.photos/id/23/160/120',
    totalStock: 3,
  ),
  const ProductModel(
    id: 4,
    name: 'Fashion Shoes Men',
    categoryName: "Man's Fashion",
    rating: 3,
    price: 39.0,
    offer: 55,
    offerPrice: 85,
    image: 'https://picsum.photos/id/27/160/120',
    totalStock: 0,
  ),
];
final faqList = [
  FaqModel(
    id: 0,
    title: ' What exactly is Topcommors App?',
    question:
        "Of course. It's your app and it completely belongs to you. We have provided few options to customize the app. You may find the customization features on the app's dashboard, which will allow",
  ),
  FaqModel(
    id: 1,
    title: ' What exactly is Topcommors App?',
    question:
        "Of course. It's your app and it completely belongs to you. We have provided few options to customize the app. You may find the customization features on the app's dashboard, which will allow",
  ),
  FaqModel(
    id: 2,
    title: ' What exactly is Topcommors App?',
    question:
        "Of course. It's your app and it completely belongs to you. We have provided few options to customize the app. You may find the customization features on the app's dashboard, which will allow",
  ),
  FaqModel(
    id: 3,
    title: ' What exactly is Topcommors App?',
    question:
        "Of course. It's your app and it completely belongs to you. We have provided few options to customize the app. You may find the customization features on the app's dashboard, which will allow",
  ),
  FaqModel(
    id: 4,
    title: ' What exactly is Topcommors App?',
    question:
        "Of course. It's your app and it completely belongs to you. We have provided few options to customize the app. You may find the customization features on the app's dashboard, which will allow",
  ),
];
